### PR TITLE
Add MetachainCreated event

### LINKED ISSUE #55: Add MetachainCreated event in Consensus contract
Add **MetachainCreated** event in consensus contract.
It should emit **chainid** in the contract.
Also, remove check in Core contract's setup method where **accumulatedGas** is not allowed as 0. 
https://github.com/mosaicdao/mosaic-1/blob/feature/consensus/contracts/core/Core.sol#L328

fixes #55

### PR DESCRIPTION
**Pull request by gulshanvasnani**
PR contains changes to add :
1. **metachainCreated** event in consensus contract.
2. Allow accumulatedGas to be 0 in Core's setup method.
3. Added unit test to assert metachain created event.
fixes #55

### CODE REVIEW

**Review by pgev — CHANGES_REQUESTED** [review]
Thanks for changes @gulshanvasnani. In the new proposal (https://hackmd.io/HPfjQEZKQh-lUCCP_NhYug?view#Tickets point 5) `Axiom::newMetachain` should emit MetachainCreated event. Please, update corresponding ticket and implementation accordingly. Thx.

**Review by benjaminbollen — APPROVED** [review]
LGTM; ☝️ pro's remark; metachainId will become `bytes32` in your later PR; perhaps merge/align the two

**Review by pgev — APPROVED** [review]

**Comment by pgev** [comment]
@gulshanvasnani please resolve conflicts.

**Comment by gulshanvasnani** [comment]
Closing it as it will be taken up in https://github.com/mosaicdao/mosaic-1/issues/100

**Pull request closed without merging**
