### PR TITLE
Fix ganache failing tests 

### LINKED ISSUE #102: Debug the failing unit tests.
The unit tests are randomly failing. 
Debug the logs and find the root cause. 

The failing unit tests are random. One of the failing logs is as follows.

```
1) Contract: Reputation::slash
       should fail if validator has already withdrawn:
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
  2) Contract: Reputation::stake
       should fail to stake validator pool if wETH token is not approved:
     
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
  Error:     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.approve (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:170:1)
      at Context.it (test/reputation/stake.js:190:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
  3) Contract: Reputation::stake
       "after each" hook: after test for "should fail to stake validator pool if wETH token is not approved":
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
  4) Contract: Reputation::withdraw
       "before all" hook: prepare suite:
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)


```

### PR DESCRIPTION
**Pull request by abhayks1**
PR covers fix for failing unit tests on ganache
- There is internal package issue with Web3 version>= 1.2.2. 
- In the PR web3 version is updated to 1.2.1.  Truffle version is updated to 5.0.43
- More details: 
   https://github.com/ethereum/web3.js/issues/3266
   https://github.com/trufflesuite/truffle/issues/2654
   https://github.com/trufflesuite/ganache-cli/issues/702
   

Fixes #102

### CODE REVIEW

**Comment by cgewecke** [comment]
@abhayks1 Did they crash with the same problem? If so does it go away if you go back to Truffle 5.1.x and Web3 1.2.4, but go down below 6.7.0 for ganache?

**Comment by abhayks1** [comment]
@cgewecke test passes with below package versions:
```
"ganache-cli": "6.8.1-beta.0",
"truffle": "5.0.43",
"web3": "1.2.1",
```
Can you please explain the issue in more details?

**Comment by cgewecke** [comment]
Ah! Perfect. Thanks - that's all I wanted to know. :)

**Comment by abhayks1** [comment]
@cgewecke I can try below:
```
If so does it go away if you go back to Truffle 5.1.x and Web3 1.2.4, but go down below 6.7.0 for ganache?
```
Can you Please explain issue in more details?

**Comment by cgewecke** [comment]
@abhayks1 I'm sorry - I thought I saw the tests fail! But they passed - so just downgrading Truffle and Web3 works I think.

**Comment by abhayks1** [comment]
@cgewecke confirmed that below package combination doesn't work and tests fail.
```
 "ganache-cli": "6.7.0",
 "truffle": "5.1.3",
 "web3": "1.2.4"
```

below package combination works. Hope it helps others too.
```
"ganache-cli": "6.8.1-beta.0",
"truffle": "5.0.43",
"web3": "1.2.1",
```

**Review by deepesh-kn — APPROVED** [review]
LGTM 👍

**Pull request merged**
