### PR TITLE
Implementation of getRemoteGatewayLatestProvenBlockNumber

### LINKED ISSUE #303: Gateways should expose view function to get remoteGatewayLastProvenBlockNumber
As a Dapp like facilitator, 

I should be able to fetch remote gateway last proven block number from gateways(EIP20Gateway, EIP20Cogateway, ConsensusGateway and ConsensusCogateway), 

So that,  I can make message transfer transactions.

### PR DESCRIPTION
**Pull request by abhayks1**
- Implementation of getRemoteGatewayLatestProvenBlockNumber in ERC20Gateway, ERC20Cogateway, ConsensusGateway and ConsensusCogateway.

Fixes #303

### CODE REVIEW

**Comment by 0xsarvesh** [comment]
@abhayks1  can you please add some tests to validate if it works. Thanks

**Comment by abhayks1** [comment]
> @abhayks1 can you please add some tests to validate if it works. Thanks

@sarvesh-ost assertions added.

**Review by benjaminbollen — CHANGES_REQUESTED** [review]
why did you not implement it once in `Proof.sol`?

**Comment by abhayks1** [comment]
Closing this PR as ticket description has changed. Will put comment in the ticket.

**Pull request closed without merging**
